apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iperf3-lib-observability
resources:
  - namespace.yaml
  - stack.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml
  - name: grafana-datasources
    files:
      - datasources.yml
  - name: grafana-providers
    files:
      - dashboards.yml
  - name: grafana-dashboard
    files:
      - dashboard.json
