apiVersion: v1
kind: Namespace
metadata:
  name: iperf3-lib-observability
  labels:
    app.kubernetes.io/part-of: iperf3-lib-observability
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.36
